version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        BACKEND_HOST_PORT: backend:5000
    depends_on:
      - backend
    ports:
      - "8000:80"
  redis:
    image: "redis:alpine"
