ARG FRONTEND_BASE_URL=""
ARG BACKEND_BASE_URL=""
ARG BACKEND_BASE_SOCKET_URL=""

FROM node:14-alpine AS build
WORKDIR /app
COPY . .
RUN yarn
RUN yarn global add parcel-bundler
RUN rm -fr dist .env .env.production
ENV NODE_ENV=production
RUN parcel build src/frontend/index.html



FROM nginx:alpine
ARG BACKEND_HOST_PORT
COPY --from=build /app/dist/ /usr/share/nginx/html/
COPY generate-nginx-config.sh /
RUN sh generate-nginx-config.sh > /etc/nginx/conf.d/default.conf
