version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
  redis:
    image: "redis:alpine"

volumes:
  caddy_data:
  caddy_config:
